include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules for better code quality
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
