name: universal_downloader
description: A Flutter package for downloading files on all platforms (Android, iOS, Web, Windows, macOS, Linux) with progress tracking and comprehensive error handling.
version: 1.0.1
homepage: https://github.com/himanshujjp/universal_downloader
repository: https://github.com/himanshujjp/universal_downloader
documentation: https://github.com/himanshujjp/universal_downloader#readme
issue_tracker: https://github.com/himanshujjp/universal_downloader/issues

topics:
  - download
  - file
  - http
  - network
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.0
  path: ^1.9.0
  permission_handler: ^12.0.0
  device_info_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
